<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRO70x9t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRO70x9t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRO70x9t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRO70x9t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRO70x9t\App_KernelDevDebugContainer([
    'container.build_hash' => 'RO70x9t',
    'container.build_id' => '54390e76',
    'container.build_time' => 1585910598,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRO70x9t');
