<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerANIvoSO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerANIvoSO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerANIvoSO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerANIvoSO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerANIvoSO\App_KernelDevDebugContainer([
    'container.build_hash' => 'ANIvoSO',
    'container.build_id' => '6632ee89',
    'container.build_time' => 1588531329,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerANIvoSO');
