<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1DmvQQO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1DmvQQO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1DmvQQO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1DmvQQO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1DmvQQO\App_KernelDevDebugContainer([
    'container.build_hash' => '1DmvQQO',
    'container.build_id' => 'e5475bba',
    'container.build_time' => 1590092590,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1DmvQQO');
